# Site settings
name: Fitrah Aditiya
title: Fitrah Aditiya | Front End X Back End Developer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://nvrmnd.pw/
baseurl: 'https://nvrmnd.pw/'
email: hi@nvrmnd.pw
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:hi@nvrmnd.pw
  - title: instagram
    url: https://instagram.com/nynpaaf_
  - title: github
    url: https://github.com/nvrmndotpw

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
